// Find the Difference

// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.

// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.


var findTheDifference = function(s, t) {
    var dict = {};
    for(var idx=0; idx<s.length; idx++){
        if(s[idx] in dict){
            dict[s[idx]]++
        } else {
            dict[s[idx]]=1
        }
    }
    for(var idx=0;idx<t.length; idx++){
        if(t[idx] in dict){
            dict[t[idx]]--;
        } else {
            return t[idx]
        }
    }
    for(var key in dict){
        if(dict[key] !== 0 ){
            return key
        }
    }
};
